FROM webhippie/php-caddy:latest@sha256:e6bb6335532fb0b60dd8ea9aa4e0815ca4cc7c6f3a1f4e196e0abfd74e8b72b2

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Piwik" \
  org.label-schema.vcs-url="https://github.com/dockhippie/piwik.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 8080

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  apk add php7-ldap && \
  rm -rf /var/cache/apk/* && \
  curl -sLo - http://builds.piwik.org/piwik-3.8.1.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  chown -R caddy:caddy /srv/www

COPY ./overlay ./overlay-amd64 /
