FROM ghcr.io/dockhippie/php-apache:8.4-arm@sha256:72876425f1a9a360770f2df248eb7352967f8b18d43e45541054fd01f6a9a224

VOLUME ["/var/lib/piwik"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV PIWIK_VERSION=3.6.1

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.36

RUN curl -sSLo - http://builds.matomo.org/piwik-${PIWIK_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-arm && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
