FROM ghcr.io/dockhippie/php-apache:8.4-arm64@sha256:1736b09a0f09d79a492c7d7aa969bbc9869d4b036ad1f0ca201f7a18a66529f2

VOLUME ["/var/lib/piwik"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV PIWIK_VERSION=3.10.0

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.39

RUN curl -sSLo - http://builds.matomo.org/piwik-${PIWIK_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-arm64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
