FROM webhippie/php-caddy:latest-arm64v8@sha256:12acc6c6a40f195e5af7c0b7d3673266477b7df2e7ed08afd86a3508d857bc87

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Piwik" \
  org.label-schema.vcs-url="https://github.com/dockhippie/piwik.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 8080

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  apk add php7-ldap && \
  rm -rf /var/cache/apk/* && \
  curl -sLo - http://builds.piwik.org/piwik-3.4.0.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  chown -R caddy:caddy /srv/www

COPY ./overlay ./overlay-arm64v8 /
