FROM webhippie/php-caddy:latest@sha256:554b76f5e0513a44e5a6e9e22b790066eac158f62725796eb61b8a5969f84bf3

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Piwik" \
  org.label-schema.vcs-url="https://github.com/dockhippie/piwik.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 8080

WORKDIR /srv/www
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

ENV CRON_ENABLED true

RUN apk update && \
  apk upgrade && \
  apk add php7-ldap && \
  rm -rf /var/cache/apk/* && \
  curl -sLo - http://builds.piwik.org/piwik-3.4.0.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  chown -R caddy:caddy /srv/www

COPY ./overlay ./overlay-amd64 /
