FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:bf92e24e6c46fb3cb853210990299d87f40df235b1a594bd2512cb47cb622d40

VOLUME ["/var/lib/piwik"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=kanboard/kanboard
ENV PIWIK_VERSION=3.4.0

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.36

RUN curl -sSLo - http://builds.matomo.org/piwik-${PIWIK_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
